window:
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 10
    y: 10

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Allow terminal applications to change Alacritty’s window title.
window.dynamic_title: true

cursor:
  style: Block
  blinking: On
  unfocused_hollow: true

live_config_reload: true

font:
  normal:
    family: Menlo
    style: Regular
  bold:
    family: Menlo
    style: Bold
  italic:
    family: Menlo
    style: Italic
  bold_italic:
    family: Menlo
    style: Bold Italic
  size: 12
  use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

colors:
  # Default colors
  primary:
    background: "0x1b182c"
    foreground: "0xcbe3e7"

  # Normal colors
  normal:
    black: "0x100e23"
    red: "0xff8080"
    green: "0x95ffa4"
    yellow: "0xffe9aa"
    blue: "0x91ddff"
    magenta: "0xc991e1"
    cyan: "0xaaffe4"
    white: "0xcbe3e7"

  # Bright colors
  bright:
    black: "0x565575"
    red: "0xff5458"
    green: "0x62d196"
    yellow: "0xffb378"
    blue: "0x65b2ff"
    magenta: "0x906cff"
    cyan: "0x63f2f1"
    white: "0xa6b3cc"
